### PR TITLE
fix(tests): follow-up on tj/node-growl#62

### PR DESCRIPTION
**Pull request by faust64**
as suggested by @deiga, tests do not pass since last PR was merged, ...

### CODE REVIEW

**Comment by deiga** [comment]
Thank you for your contibution, but I already fixed this on my own. :)

**Comment by faust64** [comment]
Trying to update mocha with latest growl from npmjs, tests fail regardless of nodejs version:
https://travis-ci.org/mochajs/mocha/builds/253458115

I'll check tomorrow, although I remember successfully testing my patch against mocha earlier today.

**Comment by deiga** [comment]
@faust64 I believe that the tests fail for mocha, because you don't have `libnotify-bin` on the travis box

**Comment by faust64** [comment]
I very much doubt that. mocha tests were passing prior to updating node-growl.

as of 1.10.1, tests started passing back with node >=6. Still broken with node5, node4, iojs, node0.*

```
==> [Test :: Unit]
"bin/mocha" test/unit/*.spec.js \
		test/node-unit/*.spec.js \
		--growl
/home/travis/build/faust64/mocha/node_modules/growl/lib/growl.js:13
let cmd;
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode```

Again, I don't think we can blame travis here.

**Comment by deiga** [comment]
@faust64 I wasn't trying to shift blame. I just tried it on a linux box of my own and found that issue with a missing `libnotify-bin`. If it's still broken then I will try to resolve this.

I've been waiting for @tj to either give admin access to the repo or to enable the repo on travis, so that I can do actual testing. 

I'll do some testing and figure out what's wrong

**Comment by deiga** [comment]
@faust64 Those issues should now be fixed

**Comment by faust64** [comment]
indeed. Now it fails on some const:
```
"bin/mocha" test/unit/*.spec.js \
		test/node-unit/*.spec.js \
		--growl
/home/travis/build/faust64/mocha/node_modules/growl/lib/growl.js:9
const spawn = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.```

(https://travis-ci.org/faust64/mocha/jobs/254231486)

**Comment by deiga** [comment]
@faust64 I'm sorry, but I removed support for node version below 4.0, so that's why that test fails.

**Comment by faust64** [comment]
so... we've been waiting for a security fix (for months), and now you're telling us we can't apply it. nice...
I guess we'll have to fork, then.

**Comment by deiga** [comment]
@faust64 Why would you even support Node.js <4 at this point in time? It is utterly unsecure to run any version lower than 4.8.4

**Comment by deiga** [comment]
But if you desire to run it on lower node versions then you would need to use the `--harmony` flag when starting node

**Pull request closed without merging**
