### PR TITLE
fix(lib): fixed command injection vulnerability according to Issue #60

### PR DESCRIPTION
**Pull request by keymandll**
After discussing the command injection issue with [cristianstaicu](https://github.com/cristianstaicu) I have fixed the code.
To summarize the changes:
- Eliminated the use of the _quote()_ functions. The _args_ array is now handled by the shell-escape lib.
- Updated the _packages.json_ and added _shell-escape_ as dependency
- Fixed version number inconsistency between _growl.js_ and _packages.json_, also incremented by _0.0.1_
- Updated history file to reflect the relevant changes.

### CODE REVIEW

**Comment by evilpacket** [comment]
@keymandll any chance we can get this merged and 1.9.3 shipped to address the vuln?

**Comment by marcysutton** [comment]
We'll have to remove this module if this isn't fixed, as the vulnerability is failing our builds now. Just so you know people are depending on it!

**Comment by nabajit-cpu** [comment]
Where can I find the patch file ?

**Comment by ad-zsolt-imre** [comment]
All. It's been a while I opened this PR. If it did not get merged and the updates published since, unfortunately there's nothing I can do. I'm not a maintainer of this project. 

I'd recommend either removing this package from your dependencies or forking it and applying the changes (See "Files changed" tab of the PR) submitted and using your fork.

**Pull request closed without merging**
