### PR TITLE
Adds travis CI support

### PR DESCRIPTION
**Pull request by deiga**

### CODE REVIEW

**Comment by deiga** [comment]
@tj Can you enable travis CI for me or can you give me enough permissions, to do it myself? :)

**Comment by deiga** [comment]
@tj Sorry to be a bother, but could you respond to this? :)

**Comment by tj** [comment]
should be good to go now

**Comment by lbeschastny** [comment]
Shouldn't `eslint-plugin-node` be a `devDependency`?

Right not this PR cause the following warning after installing the latest `node-growl` from `npm`:

    npm WARN eslint-plugin-node@5.1.1 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.

**Pull request merged**
